# -Dapollo_profile=dev -Ddev_meta=http://localhost:8080/
server: 
  port: 8070
spring: 
  datasource: 
    url: jdbc:mysql://localhost:3306/ApolloPortalDB?characterEncoding=utf8
    username: root
    password: root
